
var CONST = module.exports;

CONST.LOG_WARNING = "game_warning";
CONST.LOG_EXCEPTION = "game_exception";
CONST.LOG_WEBMSG = "game_webmsg";

//for db collections name
CONST.GID_DB = "gid";
CONST.USER_DB = "user";

//max offline user cache
CONST.MAX_USERCACHE = 100000;
CONST.REMOVE_NUM = 500; 
CONST.PRELOAD_NUM = 80000;

CONST.CLIENT_SIGN_EXPIRE = 30000;
CONST.SERVER_KEY = "client_key";

//************************************************************************************
//for client to server msg
//************************************************************************************
//for client to server msg
CONST.CS_MSG = {};
CONST.CS_MSG.CLIENT_HB = 66666;
CONST.CS_MSG.VERIFYCONNECTION = 10000; //verifyconnection
CONST.CS_MSG.WEIXINCHATRECORD = 10001; //weixinchatrecord
CONST.CS_MSG.CHAT = 10002; //chat
CONST.CS_MSG.CHATBROADCAST = 10003; //broadcast
CONST.CS_MSG.DATATABLE = 10004; //
CONST.CS_MSG.SYNCGOLD = 10005; //
CONST.CS_MSG.VIEWPLAYER = 10006; //viewplayer
CONST.CS_MSG.ROOMCLOSE = 10007;// 房间关闭

CONST.SC_MSG = {};
CONST.SC_MSG.VERIFYCONNECTION = 20000; //verifyconnection
CONST.SC_MSG.WEIXINCHATRECORD = 20001; //weixinchatrecord
CONST.SC_MSG.CHAT = 20002; //chat
CONST.SC_MSG.CHATBROADCAST = 20003; //broadcast
CONST.SC_MSG.DATATABLE = 20004; //
CONST.SC_MSG.SYNCGOLD = 20005; //
CONST.SC_MSG.VIEWPLAYER = 20006; //viewplayer
CONST.SC_MSG.ROOMCLOSE = 20007;// 房间关闭

//************************************************************************************
//game_server与web这边的通信
//************************************************************************************
CONST.SW_MSG = {};
CONST.SW_MSG.INFO = 8000; //服务器信息
CONST.SW_MSG.LOGIN = 8001; //登录返回
CONST.SW_MSG.REGISTER = 8002; //注册返回register
CONST.SW_MSG.SELFINFORMATION = 8003; //个人信息
CONST.SW_MSG.MODIFYNAME = 8004; //修改昵称
CONST.SW_MSG.MODIFYPWD = 8005; //修改密码
CONST.SW_MSG.TRANSFERGOLD = 8006; //转分
CONST.SW_MSG.TRANSFERRECORD = 8007; //转分记录
CONST.SW_MSG.BANK = 8008; //银行
CONST.SW_MSG.BANDINGBANKCARD = 8009; //绑定银行卡
CONST.SW_MSG.SAFEBOX = 8010; //保险箱
CONST.SW_MSG.SAFEBOXSTORE = 8011; //保险箱存入
CONST.SW_MSG.SAFEBOXDRAWOUT = 8012; //保险箱取出
CONST.SW_MSG.RECHARGEDETAIL = 8013; //充值明细
CONST.SW_MSG.WITHDRAWCASH = 8014; //提现
CONST.SW_MSG.PHONEBETDATA = 8015; //电话投注数据
CONST.SW_MSG.PHONEBET = 8016; //电话投注
CONST.SW_MSG.CHAT = 8017; //聊天
CONST.SW_MSG.CHATBROADCAST = 8018; //broadcast
CONST.SW_MSG.CHATRECORD = 8019; //聊天记录
CONST.SW_MSG.DATATABLE = 8020; //
CONST.SW_MSG.NOTICE = 8021; //公告
CONST.SW_MSG.CHECKQRCODE = 8022; //检测二维码
CONST.SW_MSG.MODIFYTWOPWD = 8023; //修改二级密码
CONST.SW_MSG.RECHARGECTL = 8024; //支付控制
CONST.SW_MSG.PUSHGOLD = 8025; //推送玩家积分
CONST.SW_MSG.FINDPASSWORD = 8026; //找回密码
CONST.SW_MSG.FINDTWOPWD = 8027; //找回二级密码
CONST.SW_MSG.PLAYERLIST = 8028; //玩家列表
CONST.SW_MSG.ROOMCHECK = 8029; //房间检查
CONST.SW_MSG.KICKPLAYER = 8030; //房间踢人
CONST.SW_MSG.GETSPREAD = 8031; //获取推广配置
CONST.SW_MSG.USERSPREAD = 8032; //获取玩家收益信息
CONST.SW_MSG.RECEIVE = 8033; //领取玩家收益
CONST.SW_MSG.TOTALSUM = 8034; //历史推广人数
CONST.SW_MSG.TODAYSUM= 8035; //今日推广人数
CONST.SW_MSG.YESTERDAYPROFIT = 8036; //昨日收益
CONST.SW_MSG.TODAYPROFIT= 8037; //今日收益
CONST.SW_MSG.WEEKPROFIT = 8038; //本周收益
CONST.SW_MSG.LASTWEEKPROFIT= 8039; //上周收益
CONST.SW_MSG.MONTHPROFIT = 8040; //本月收益
CONST.SW_MSG.SUBDETAILED = 8041; //下级详情
CONST.SW_MSG.FOOTBALLURL = 8042; //足球下注URL
CONST.SW_MSG.PICICODE = 8043; //获取图片验证码
CONST.SW_MSG.ISBINDSECURITY = 8044; //是否绑定密保
CONST.SW_MSG.BINDSECURITY = 8045; //绑定密保
CONST.SW_MSG.GETACTIVITY = 8046; //获取活动列表
CONST.SW_MSG.GETCAROUSEL = 8047; //获取轮播图
CONST.SW_MSG.GETGUIDE = 8048; //获取新手指南
CONST.SW_MSG.GETDETAILED = 8049; //获取个人流水
CONST.SW_MSG.GETARTICLE = 8050; //获取文章详情

CONST.WS_MSG = {};
CONST.WS_MSG.INFO = 9000; //服务器信息
CONST.WS_MSG.LOGIN = 9001; //登录返回
CONST.WS_MSG.REGISTER = 9002; //注册返回register
CONST.WS_MSG.SELFINFORMATION = 9003; //个人信息
CONST.WS_MSG.MODIFYNAME = 9004; //修改昵称
CONST.WS_MSG.MODIFYPWD = 9005; //修改密码
CONST.WS_MSG.TRANSFERGOLD = 9006; //转分
CONST.WS_MSG.TRANSFERRECORD = 9007; //转分记录
CONST.WS_MSG.BANK = 9008; //银行
CONST.WS_MSG.BANDINGBANKCARD = 9009; //绑定银行卡
CONST.WS_MSG.SAFEBOX = 9010; //保险箱
CONST.WS_MSG.SAFEBOXSTORE = 9011; //保险箱存入
CONST.WS_MSG.SAFEBOXDRAWOUT = 9012; //保险箱取出
CONST.WS_MSG.RECHARGEDETAIL = 9013; //充值明细
CONST.WS_MSG.WITHDRAWCASH = 9014; //提现
CONST.WS_MSG.PHONEBETDATA = 9015; //电话投注数据
CONST.WS_MSG.PHONEBET = 9016; //电话投注
CONST.WS_MSG.CHAT = 9017; //聊天
CONST.WS_MSG.CHATBROADCAST = 9018; //broadcast
CONST.WS_MSG.CHATRECORD = 9019; //聊天记录
CONST.WS_MSG.DATATABLE = 9020; //
CONST.WS_MSG.NOTICE = 9021; //公告
CONST.WS_MSG.CHECKQRCODE = 9022; //检测二维码
CONST.WS_MSG.MODIFYTWOPWD = 9023; //修改二级密码
CONST.WS_MSG.RECHARGECTL = 9024; //支付控制
CONST.WS_MSG.PUSHGOLD = 9025; //推送玩家积分
CONST.WS_MSG.FINDPASSWORD = 9026; //找回密码
CONST.WS_MSG.FINDTWOPWD = 9027; //找回二级密码
CONST.WS_MSG.PLAYERLIST = 9028; //玩家列表
CONST.WS_MSG.ROOMCHECK = 9029; //房间检查
CONST.WS_MSG.KICKPLAYER = 9030; //房间踢人
CONST.WS_MSG.GETSPREAD = 9031; //获取推广配置
CONST.WS_MSG.USERSPREAD = 9032; //获取玩家收益信息
CONST.WS_MSG.RECEIVE = 9033; //领取玩家收益
CONST.WS_MSG.TOTALSUM = 9034; //历史推广人数
CONST.WS_MSG.TODAYSUM = 9035; //今日推广人数
CONST.WS_MSG.YESTERDAYPROFIT = 9036; //昨日收益
CONST.WS_MSG.TODAYPROFIT = 9037; //今日收益
CONST.WS_MSG.WEEKPROFIT = 9038; //本周收益
CONST.WS_MSG.LASTWEEKPROFIT = 9039; //上周收益
CONST.WS_MSG.MONTHPROFIT = 9040; //本月收益
CONST.WS_MSG.SUBDETAILED = 9041; //下级详情
CONST.WS_MSG.FOOTBALLURL = 9042; //足球下注URL
CONST.WS_MSG.PICICODE = 9043; //获取图片验证码
CONST.WS_MSG.ISBINDSECURITY = 9044; //是否绑定密保
CONST.WS_MSG.BINDSECURITY = 9045; //绑定密保
CONST.WS_MSG.GETACTIVITY = 9046; //获取活动列表
CONST.WS_MSG.GETCAROUSEL = 9047; //获取轮播图
CONST.WS_MSG.GETGUIDE = 9048; //获取新手指南
CONST.WS_MSG.GETDETAILED = 9049; //获取个人流水
CONST.WS_MSG.GETARTICLE = 9050; //获取文章详情
//************************************************************************************
//ERROR_CODE
//************************************************************************************
CONST.ERROR_CODE = {};
CONST.ERROR_CODE.ERROR_UNKNOWN          = 10000; //未知错误
CONST.ERROR_CODE.NO_FOUND               = 10001; //数据不存在
CONST.ERROR_CODE.SUCCESS                = 10002; //处理成功
CONST.ERROR_CODE.FAILURE                = 10003; //处理失败
CONST.ERROR_CODE.ERROR_DATA             = 10004; //数据异常
CONST.ERROR_CODE.AUTHENTICATION_FAILURE = 20000; //鉴权失败
CONST.ERROR_CODE.ILLEGAL_ARGUMENT       = 20001; //不合法参数
CONST.ERROR_CODE.ERROR_PHONE_EXISTS     = 20002; //该手机号已被注册
CONST.ERROR_CODE.ERROR_PHONE_ERROR      = 20003; //手机号不正确
CONST.ERROR_CODE.ERROR_CODE_ERROR       = 20004; //验证码错误 
CONST.ERROR_CODE.ERROR_ACCOUNT_ERROR    = 20005; //账号或密码错误
CONST.ERROR_CODE.ERROR_ACCOUNT_NOT_EXISTS = 20006; //该账号不存在
CONST.ERROR_CODE.ERROR_BANK_EXISTS      = 20007; //银行卡信息已存在
CONST.ERROR_CODE.ERROR_WITHDRAWAL_FAIL  = 20008; //申请提现失败
CONST.ERROR_CODE.ERROR_NOT_AGENT        = 20009; //代理不存在
CONST.ERROR_CODE.ERROR_USER_NAME        = 20011; //用户名不合规范或已被注册
CONST.ERROR_CODE.ERROR_PASSWORD         = 20012; //密码不合规范
CONST.ERROR_CODE.ERROR_NAME             = 20013; //昵称不合规范
CONST.ERROR_CODE.ERROR_EMAIL            = 20014; //邮箱不合规范或已被绑定
CONST.ERROR_CODE.ERROR_PHONE_NUM        = 20015; //手机号不合规范或已被绑定
CONST.ERROR_CODE.ERROR_INVITECODE       = 20016; //邀请码错误或不存在
CONST.ERROR_CODE.ERROR_PASSWORD_REPEAT  = 20017; //新密码不能和原密码相同
CONST.ERROR_CODE.ERROR_DATA_NOT_FOUND   = 30001; //相关数据没有找到
CONST.ERROR_CODE.ERROR_ACCOUNT_LOCKED   = 30002; //账户被禁用
CONST.ERROR_CODE.ERROR_NO_LOGIN         = 30003; //没有登录
CONST.ERROR_CODE.ERROR_MONEY_NOT_ENOUGH = 30004; //余额不足
CONST.ERROR_CODE.ERROR_NOT_ALLOW        = 30005; //不允许的操作
CONST.ERROR_CODE.ERROR_ACCOUNT_EXCEPTION = 30006; //账号异常
CONST.ERROR_CODE.ERROR_MAINTENANCE       = 30007; //服务器维护中
CONST.ERROR_CODE.ERROR_INVITATIONMSG     = 30008; //该邀请码已经使用
CONST.ERROR_CODE.ERROR_INVITATIONONMSG   = 30009; //已绑定邀请码
CONST.ERROR_CODE.ERROR_COUNT_NOT_ENOUGH  = 30010; //领取次数不足
CONST.ERROR_CODE.ERROR_ROOM_NOT_EXISTS   = 40008; //房间不存在
CONST.ERROR_CODE.ERROR_FULL              = 40009; //人数已满
CONST.ERROR_CODE.ERROR_DELETE_FREQUENT   = 40010; //解散太频繁
CONST.ERROR_CODE.ERROR_USER_LITTLE       = 40011; //人数太少
CONST.ERROR_CODE.ERROR_ALREADY_STARTED   = 40012; //游戏已经开始
CONST.ERROR_CODE.ERROR_ALREADY_INGAME    = 40013; //已经在其他游戏中
CONST.ERROR_CODE.ERROR_NOT_JOINGAME      = 40014; //该房间游戏开始后禁止加入
CONST.ERROR_CODE.ERROR_ACC_NOTFORMAL     = 50000; //不是正式账号
CONST.ERROR_CODE.DOUBLEBET_FAIL          = 50001; //双倍下注失败
CONST.ERROR_CODE.REPEATBET_FAIL          = 50002; //重复下注失败
CONST.ERROR_CODE.ROOM_NOBETZXSAMETIME    = 50003; //不能同时下注庄和闲
CONST.ERROR_CODE.ALREADY_INOTHERROOM     = 50004; //已经在其它房间并且下了注的
CONST.ERROR_CODE.ALREADYBET_NOEXIT       = 50005; //已经下注禁止退出
CONST.ERROR_CODE.ERR_REDLIMIT            = 50006; //被限红
CONST.ERROR_CODE.STAGE_NOBET             = 50007; //不在下注阶段
CONST.ERROR_CODE.NOT_SITDOWN             = 50008; //没有坐下
CONST.ERROR_CODE.ROOM_NOTOPEN            = 50009; //房间关闭了
CONST.ERROR_CODE.NOT_INROOM              = 50010; //没有在该房间中
CONST.ERROR_CODE.ALREADY_SIGN            = 50011; //今日已签到
CONST.ERROR_CODE.NOWHEELTIMES            = 50012; //没有转盘次数
CONST.ERROR_CODE.NOONLINERECVTIMES       = 50013; //没有在线奖励领取次数
CONST.ERROR_CODE.ONLINEREWARDERR         = 50014; //在线奖励领取时间未到
CONST.ERROR_CODE.NOALMSTIMES             = 50015; //没有救济金可领取次数
CONST.ERROR_CODE.ALMS_LIMIT              = 50016; //救济金领取条件不符合
CONST.ERROR_CODE.ALREADY_FRIEND          = 50017; //已经是好友
CONST.ERROR_CODE.FRIEND_FULL             = 50018; //好友满了
CONST.ERROR_CODE.OPPO_FRIEND_FULL        = 50019; //对方好友满了
CONST.ERROR_CODE.FRIEND_APPLY_SEND       = 50020; //好友申请已发送
CONST.ERROR_CODE.FRIEND_APPLY_INVALID    = 50021; //申请已经失效
CONST.ERROR_CODE.FRIEND_NOT_EXIST        = 50022; //好友不存在
CONST.ERROR_CODE.TASK_NOTCOMPLETE        = 50023; //任务未完成
CONST.ERROR_CODE.TASK_ALREADYRECV        = 50024; //任务已领取
CONST.ERROR_CODE.TASK_INVALID            = 50025; //任务已失效
CONST.ERROR_CODE.ROLE_LEAVE_ROOM         = 50026; //玩家已经离开房间
CONST.ERROR_CODE.ZJHPREPARE_NOEXIT       = 50027; //炸金花已经准备禁止退出
CONST.ERROR_CODE.ZJHSTAGE_ERR            = 50028; //炸金花阶段不对
CONST.ERROR_CODE.ZJH_ALREADY_PREPARE     = 50029; //炸金花已经打底
CONST.ERROR_CODE.ZJH_NOTTURN             = 50030; //炸金花不该你发话
CONST.ERROR_CODE.ZJH_ALREADYLOOK         = 50031; //炸金花已经看牌了
CONST.ERROR_CODE.ZJH_NOTPLAY             = 50032; //玩家这把根本就没玩
CONST.ERROR_CODE.ZJH_BETSUMERR           = 50033; //下注金额有误
CONST.ERROR_CODE.ZJH_SELFABANDON         = 50034; //炸金花自己已经弃牌
CONST.ERROR_CODE.ZJH_OPPOABANDON         = 50035; //炸金花对手已经弃牌
CONST.ERROR_CODE.BRN_HASBANKER           = 50036; //已经有人上庄了
CONST.ERROR_CODE.BRN_BETLIMIT            = 50037; //下注限额
CONST.ERROR_CODE.BRN_YOUNOTBANKER        = 50038; //你不是庄家

CONST.ERR_MSG = {};
CONST.ERR_MSG.SERVER_CLOSE = "服务器已关闭";
CONST.ERR_MSG.SIGN_ERR = "数据错误，请重新登录。";
CONST.ERR_MSG.SIGN_EXPIRE = "登录过期，请重新登录。";
CONST.ERR_MSG.NO_LOGIN = "该账号已登录，请稍后再试。";
CONST.ERR_MSG.ESTABLISHCONNFAIL = "建立链接失败。"; //establish connection fail

CONST.CARD_COLOR = {};
CONST.CARD_COLOR.SPADE = 0;  //黑桃
CONST.CARD_COLOR.HEART = 1;  //红桃
CONST.CARD_COLOR.PLUM  = 2;  //梅花
CONST.CARD_COLOR.BLOCK = 3;  //方块


CONST.ONEPOKER = [
    [0, 1], [0, 2], [0, 3], [0, 4], [0, 5], [0, 6], [0, 7], [0, 8], [0, 9], [0, 10],
    [0, 11], [0, 12], [0, 13],
    [1, 1], [1, 2], [1, 3], [1, 4], [1, 5], [1, 6], [1, 7], [1, 8], [1, 9], [1, 10],
    [1, 11], [1, 12], [1, 13],
    [2, 1], [2, 2], [2, 3], [2, 4], [2, 5], [2, 6], [2, 7], [2, 8], [2, 9], [2, 10],
    [2, 11], [2, 12], [2, 13],
    [3, 1], [3, 2], [3, 3], [3, 4], [3, 5], [3, 6], [3, 7], [3, 8], [3, 9], [3, 10],
    [3, 11], [3, 12], [3, 13]
];

